<a href="https://colab.research.google.com/github/srikumar03/Python_numpy_Pandas/blob/main/BYTS_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
lst = [1, 2, 3, 4, 5]

lst.append(6)
print("After insertion:", lst)

lst.remove(4)
print("After deletion:", lst)

After insertion: [1, 2, 3, 4, 5, 6]
After deletion: [1, 2, 3, 5, 6]


In [ ]:
tup = (1, 2, 3, 4, 5)
nt = tup + (6,)
print("After insertion:", nt)


After insertion: (1, 2, 3, 4, 5, 6)


In [ ]:
_dict = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

_dict['f'] = 6
print("After insertion:", _dict)

del _dict['c']
print("After deletion:", _dict)

After insertion: {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}
After deletion: {'a': 1, 'b': 2, 'd': 4, 'e': 5, 'f': 6}


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)
print(type(a))
a.shape

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


(2, 2)

In [ ]:
b=np.arange(5,12)
print(b)
b=np.arange(5,50,3)
print(b)

[ 5  6  7  8  9 10 11]
[ 5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [ ]:
print(np.ones((2,5)) ,end="\n\n****\n")
print(np.zeros((2,2)) ,end="\n\n*****\n")
print(np.zeros((3,2,5)) ,end="\n\n*****\n")

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

****
[[0. 0.]
 [0. 0.]]

*****
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]

*****


In [ ]:
print(np.eye(3,3) ,end="\n\n*****\n")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

*****


In [ ]:

print(np.linspace(2,20) ,end="\n\n*****\n")
print(np.linspace(0,1) ,end="\n\n*****\n")

[ 2.          2.36734694  2.73469388  3.10204082  3.46938776  3.83673469
  4.20408163  4.57142857  4.93877551  5.30612245  5.67346939  6.04081633
  6.40816327  6.7755102   7.14285714  7.51020408  7.87755102  8.24489796
  8.6122449   8.97959184  9.34693878  9.71428571 10.08163265 10.44897959
 10.81632653 11.18367347 11.55102041 11.91836735 12.28571429 12.65306122
 13.02040816 13.3877551  13.75510204 14.12244898 14.48979592 14.85714286
 15.2244898  15.59183673 15.95918367 16.32653061 16.69387755 17.06122449
 17.42857143 17.79591837 18.16326531 18.53061224 18.89795918 19.26530612
 19.63265306 20.        ]

*****
[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69

In [ ]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b,end="\n------------\n\n")

print(b[0:3:2],end="\n------------\n\n")

print(b[0:3,1])
print(b[:,2])
print(b[0:2,1:2],end="\n------------\n\n")


[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------

[[1 2 3]
 [7 8 9]]
------------

[2 5 8]
[3 6 9]
[[2]
 [5]]
------------



In [ ]:
b=np.array([1,2,3,4,5,6])
np.argmax(b)#index

5